### ISSUE TITLE
Error generating email addresses

### ISSUE THREAD

**Issue by geoffmcalpin** [BalliAsghar/Mailsy#18]
Every time I try to generate an email address with `mailsy g`, I get the following:

```
⠼ creating...
/home/linuxbrew/.linuxbrew/Cellar/mailsy/4.0.1/libexec/lib/node_modules/mailsy/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 500
    at createError (/home/linuxbrew/.linuxbrew/Cellar/mailsy/4.0.1/libexec/lib/node_modules/mailsy/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/linuxbrew/.linuxbrew/Cellar/mailsy/4.0.1/libexec/lib/node_modules/mailsy/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/linuxbrew/.linuxbrew/Cellar/mailsy/4.0.1/libexec/lib/node_modules/mailsy/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I have already done the following:

```
brew uninstall mailsy
brew update
brew upgrade
brew doctor
brew install mailsy
```

I am using Homebrew 4.2.20 and mailsy 4.0.1 on Linux Mint 21.3

I got the exact same errors when I installed mailsy via the npm package manager: `npm install mailsy -g`

**Comment by mikekellyonline** [comment]
Geoff,

Maybe you may be able to use, `sudo apt install mailsy`. I'm not as I have not used Mint.

**Comment by geoffmcalpin** [comment]
> Geoff,
> 
> Maybe you may be able to use, `sudo apt install mailsy`. I'm not as I have not used Mint.

Thanks for the suggestion Mike. I think I may have already tried that when I was initially wanting to install it but I can't remember. I'll give it a go later this evening.

**Comment by BalliAsghar** [comment]
use npm, brew is longer supported!

**Comment by geoffmcalpin** [comment]
@BalliAsghar - if you notice from my initial message, I was getting the same message when I installed with npm as well.

**Comment by BalliAsghar** [comment]
> @BalliAsghar - if you notice from my initial message, I was getting the same message when I installed with npm as well.

Update it to the latest version and try again! Should work!

**Comment by gmcoding74** [comment]
Sorry for the late response. I updated and everything is working now!
