### ISSUE TITLE
Error when trying to use the app after installing

### ISSUE THREAD

**Issue by skill3472** [BalliAsghar/Mailsy#20]
Hey! I'm getting an error, when trying to run the app, after installing according to steps provided in the README.
Here's the error:
```
$ mailsy -h
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'fs' imported from /usr/local/lib/node_modules/mailsy/utils/index.js
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
I am running the app on 5.10.16.3-microsoft-standard-WSL2 (Ubuntu)

**Comment by BalliAsghar** [comment]
It seems there is an issue with Node.js. Try reinstalling it and ensure you're using the latest version.
